name: lifereloaded
favicon: null
layout_spectrum: 0.25182446255348623
typography_spectrum: 0.362365486798808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.24815193004906178
  lightness: 0.03555249911732972
  saturation: 0.8133546872995794
  rhythmicContrast: 0.7912637940607965
purpose: []
